name: Issues
issues:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: npm run lint
        run: npm run lint
      - name: Tests
        run: npm run test
      - name: deploy
        run: npm run deploy
      
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: deploy
        run: echo "deploying"